import { useNavigate, useParams } from "react-router-dom";

import { AppLayout } from "../../components/ui/templates/AppLayout";
import { StatusBadge } from "../../components/ui/atoms/StatusBadge";
import { Timeline } from "../../components/ui/organisms/Timeline";
import { EvidenceSection } from "../../components/ui/organisms/EvidenceSection";
import { LoadingState } from "../../components/ui/organisms/LoadingState";
import { ErrorState } from "../../components/ui/organisms/ErrorState";

import { useAdminIncidentDetail } from "../../hooks/useAdminIncidentDetail";
import { useLogout } from "../../hooks/useLogout";
import { useAuthStore } from "../../store/authStore";
import { useUnreadNotificationsCount } from "../../hooks/useUnreadNotificationsCount";

import {
  LayoutDashboard,
  FileText,
  Users,
  Tags,
  Settings,
  User,
  LogOut,
} from "../../components/ui/icons";

import { ROUTES } from "../../constants/routes";

export default function AdminIncidentDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { logout } = useLogout();
  const user = useAuthStore((state) => state.user);
  const unreadCount = useUnreadNotificationsCount();

  const { data, isLoading, isError, refetch } = useAdminIncidentDetail(id!);

  const incident = data?.incident;

  return (
    <AppLayout
      title={"Incident detail"}
      studentName={`${user?.firstName ?? ""} ${user?.lastName ?? ""}`}
      notificationCount={unreadCount}
      onProfileClick={() => navigate(ROUTES.admin.profile)}
      onNotificationsClick={() => navigate(ROUTES.admin.notifications)}
      sidebarItems={[
        { label: "Dashboard", icon: LayoutDashboard, onClick: () => navigate(ROUTES.admin.dashboard) },
        { label: "Incidents", icon: FileText, active: true, onClick: () => navigate(ROUTES.admin.incidents) },
        { label: "Users", icon: Users, onClick: () => navigate(ROUTES.admin.users) },
        { label: "Categories", icon: Tags, onClick: () => navigate(ROUTES.admin.categories) },
        { label: "Settings", icon: Settings, onClick: () => navigate(ROUTES.admin.settings) },
        { label: "Profile", icon: User, onClick: () => navigate(ROUTES.admin.profile) },
      ]}
      bottomItems={[{ label: "Logout", icon: LogOut, onClick: logout }]}
    >
      {isLoading ? (
        <LoadingState title="Loading incident..." />
      ) : isError ? (
        <ErrorState title="Failed to load incident" description="Please try again." onRetry={refetch} />
      ) : (
        <div className="mx-auto w-full max-w-4xl space-y-6">
          <button
            onClick={() => navigate(ROUTES.admin.incidents)}
            className="text-sm text-primary hover:underline"
          >
            ← Back
          </button>

          <div className="rounded-xl bg-surface p-6 shadow-sm space-y-6">
            <div>
              <h2 className="text-xl font-semibold">{incident?.title}</h2>
              <div className="mt-2 flex flex-wrap items-center gap-3 text-sm text-textSecondary">
                {incident && <StatusBadge status={incident.status} />}
                <span>#{incident?.ticket}</span>
                <span>
                  Submitted: {incident?.createdAt ? new Date(incident.createdAt).toLocaleDateString() : "—"}
                </span>
              </div>
            </div>

            <div>
              <h3 className="mb-2 text-sm font-semibold uppercase text-textSecondary">
                Description
              </h3>
              <div className="rounded-lg bg-background p-4 text-sm text-textPrimary">
                {incident?.description}
              </div>
            </div>

            {data?.attachments && data.attachments.length > 0 && (
              <div>
                <h3 className="mb-2 text-sm font-semibold uppercase text-textSecondary">
                  Evidence (submitted by student)
                </h3>
                <EvidenceSection
                  title=""
                  files={data.attachments.map((att) => ({
                    fileName: att.fileName,
                    onClick: () => {
                      window.open(att.fileUrl, "_blank", "noopener,noreferrer");
                    },
                  }))}
                />
              </div>
            )}

            {incident?.aiSummary && (
              <div>
                <h3 className="mb-2 text-sm font-semibold uppercase text-textSecondary">
                  AI Summary <span className="normal-case text-textSecondary">(Generated by AI)</span>
                </h3>
                <div className="rounded-lg border border-dashed border-border bg-background p-4 text-sm text-textPrimary">
                  {incident.aiSummary}
                </div>
              </div>
            )}

            <div>
              <h3 className="mb-1 text-sm font-semibold uppercase text-textSecondary">
                Internal notes{" "}
                <span className="text-xs font-normal normal-case text-textSecondary">
                  (Only visible to manager and admin)
                </span>
              </h3>
              <p className="mt-2 text-sm text-textSecondary">
                View only — managed by manager.
              </p>
            </div>
          </div>

          {data?.timeline && data.timeline.length > 0 && (
            <div className="rounded-xl bg-surface p-6 shadow-sm">
              <h3 className="mb-4 font-semibold">History</h3>
              <Timeline
                items={data.timeline.map((t) => ({
                  id: String(t.id),
                  title: t.statusComment,
                  description: t.changedBy,
                  timestamp: new Date(t.changedAt).toLocaleDateString(),
                }))}
              />
            </div>
          )}
        </div>
      )}
    </AppLayout>
  );
}